### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by designcouch** [MODX-Club/modx-Dropbox#5]
Completed the installation, and am able to see my Dropbox directories, modify file names, and create new directories. However, when I attempt to upload a file to Dropbox through MODX, the progress bar on upload completes, and then I get a notification that reads "internal server error" and the upload fails.

Running MODX 2.3.3 and Dropbox 2.1.2-beta

**Comment by Fi1osof** [comment]
Try to download last commit https://github.com/MODX-Club/modx-Dropbox/commit/b91d99892683cb75727c8c4ff00fc86c3e10e9f6
I think this is resolve this problem.
Package not been created yet.

**Comment by designcouch** [comment]
Indeed - that appears to have done it. Kudos!

**Comment by Fi1osof** [comment]
:)

**Comment by designcouch** [comment]
any clue when this will be committed to a new release?

**Comment by Fi1osof** [comment]
Will be soon.

**Comment by Fi1osof** [comment]
@designcouch done. Version 2.1.3
