### ISSUE TITLE
Dropbox and front end permission

### ISSUE THREAD

**Issue by brescianicri** [MODX-Club/modx-Dropbox#6]
the function getContainerList send me this error:
`Principal 0 does not have permission to load object of class modContext with primary key: mgr`
in this line:
`$hasFilePermissions = $this->hasPermission('file_list');`

is impossible for no administrator user see the list of media source.

**Comment by Fi1osof** [comment]
Just add this policy for user`s group. It`s not error for modxDropbox

**Comment by brescianicri** [comment]
The anonymous users don't have policy

**Comment by Fi1osof** [comment]
Create them.
