### ISSUE TITLE
not working anymore

### ISSUE THREAD

**Issue by funkyduke** [MODX-Club/modx-Dropbox#7]
Dropbox is now on API 2. Any change this addon for Modx will be updated? There's no alternative. Thanks.

**Comment by Fi1osof** [comment]
Sorry, no fear.

**Comment by tartakxg** [comment]
Is there plan to upgrade to v2?

**Comment by Fi1osof** [comment]
> Is there plan to upgrade to v2?

Sorry, no. I do not work with php any more.
